//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for autolevelType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="autolevelType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="feature" type="{}featureType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="slots" type="{}slotsType" minOccurs="0"/>
 *         <element name="counter" type="{}counterType" minOccurs="0"/>
 *       </choice>
 *       <attribute name="level" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="scoreImprovement" type="{}boolean" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "autolevelType", propOrder = {
        "content"
})
public class AutolevelType {

    @XmlElementRefs({
            @XmlElementRef(name = "feature", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "slots", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "counter", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "level", required = true)
    protected BigInteger level;
    @XmlAttribute(name = "scoreImprovement")
    protected String scoreImprovement;

    /**
     * Gets the value of the content property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getContent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CounterType }{@code >}
     * {@link JAXBElement }{@code <}{@link FeatureType }{@code >}
     * {@link JAXBElement }{@code <}{@link SlotsType }{@code >}
     * {@link String }
     * </p>
     *
     * @return The value of the content property.
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<>();
        }
        return this.content;
    }

    /**
     * Gets the value of the level property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setLevel(BigInteger value) {
        this.level = value;
    }

    /**
     * Gets the value of the scoreImprovement property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScoreImprovement() {
        return scoreImprovement;
    }

    /**
     * Sets the value of the scoreImprovement property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScoreImprovement(String value) {
        this.scoreImprovement = value;
    }

}
