//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for classType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="classType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded" minOccurs="0">
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="hd" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="proficiency" type="{}abilityAndSkillList"/>
 *         <element name="spellAbility" type="{}abilityEnum"/>
 *         <element name="numSkills" type="{}integer"/>
 *         <element name="autolevel" type="{}autolevelType"/>
 *         <element name="armor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="weapons" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="tools" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="slotsReset" type="{}resetEnum"/>
 *         <element name="wealth" type="{}rollFormula"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "classType", propOrder = {
        "nameOrHdOrProficiency"
})
public class ClassType {

    @XmlElementRefs({
            @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "hd", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "proficiency", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "spellAbility", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "numSkills", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "autolevel", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "armor", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "weapons", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "tools", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "slotsReset", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "wealth", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> nameOrHdOrProficiency;

    /**
     * Gets the value of the nameOrHdOrProficiency property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrHdOrProficiency property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNameOrHdOrProficiency().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AutolevelType }{@code >}
     * {@link JAXBElement }{@code <}{@link ResetEnum }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * </p>
     *
     * @return The value of the nameOrHdOrProficiency property.
     */
    public List<JAXBElement<?>> getNameOrHdOrProficiency() {
        if (nameOrHdOrProficiency == null) {
            nameOrHdOrProficiency = new ArrayList<>();
        }
        return this.nameOrHdOrProficiency;
    }

}
