//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for compendiumType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="compendiumType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="item" type="{}itemType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="race" type="{}raceType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="class" type="{}classType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="feat" type="{}featType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="background" type="{}backgroundType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="spell" type="{}spellType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="monster" type="{}monsterType" maxOccurs="unbounded" minOccurs="0"/>
 *       </choice>
 *       <attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       <attribute name="auto_indent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compendiumType", propOrder = {
        "itemOrRaceOrClazz"
})
public class CompendiumType {

    @XmlElements({
            @XmlElement(name = "item", type = ItemType.class),
            @XmlElement(name = "race", type = RaceType.class),
            @XmlElement(name = "class", type = ClassType.class),
            @XmlElement(name = "feat", type = FeatType.class),
            @XmlElement(name = "background", type = BackgroundType.class),
            @XmlElement(name = "spell", type = SpellType.class),
            @XmlElement(name = "monster", type = MonsterType.class)
    })
    protected List<Object> itemOrRaceOrClazz;
    @XmlAttribute(name = "version")
    protected Byte version;
    @XmlAttribute(name = "auto_indent")
    protected String autoIndent;

    /**
     * Gets the value of the itemOrRaceOrClazz property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOrRaceOrClazz property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getItemOrRaceOrClazz().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BackgroundType }
     * {@link ClassType }
     * {@link FeatType }
     * {@link ItemType }
     * {@link MonsterType }
     * {@link RaceType }
     * {@link SpellType }
     * </p>
     *
     * @return The value of the itemOrRaceOrClazz property.
     */
    public List<Object> getItemOrRaceOrClazz() {
        if (itemOrRaceOrClazz == null) {
            itemOrRaceOrClazz = new ArrayList<>();
        }
        return this.itemOrRaceOrClazz;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setVersion(Byte value) {
        this.version = value;
    }

    /**
     * Gets the value of the autoIndent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAutoIndent() {
        return autoIndent;
    }

    /**
     * Sets the value of the autoIndent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutoIndent(String value) {
        this.autoIndent = value;
    }

}
