//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.annotation.*;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for counterType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="counterType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded" minOccurs="0">
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="value" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="reset" type="{}resetEnum"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "counterType", propOrder = {
        "nameOrValueOrReset"
})
public class CounterType {

    @XmlElements({
            @XmlElement(name = "name", type = String.class),
            @XmlElement(name = "value", type = BigInteger.class),
            @XmlElement(name = "reset", type = ResetEnum.class)
    })
    protected List<Object> nameOrValueOrReset;

    /**
     * Gets the value of the nameOrValueOrReset property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrValueOrReset property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNameOrValueOrReset().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResetEnum }
     * {@link String }
     * {@link BigInteger }
     * </p>
     *
     * @return The value of the nameOrValueOrReset property.
     */
    public List<Object> getNameOrValueOrReset() {
        if (nameOrValueOrReset == null) {
            nameOrValueOrReset = new ArrayList<>();
        }
        return this.nameOrValueOrReset;
    }

}
