//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for featureType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="featureType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded" minOccurs="0">
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="special" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="modifier" type="{}modifierType"/>
 *         <element name="proficiency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </choice>
 *       <attribute name="optional" type="{}boolean" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "featureType", propOrder = {
        "nameOrTextOrSpecial"
})
public class FeatureType {

    @XmlElementRefs({
            @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "text", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "special", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "modifier", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "proficiency", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> nameOrTextOrSpecial;
    @XmlAttribute(name = "optional")
    protected String optional;

    /**
     * Gets the value of the nameOrTextOrSpecial property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrTextOrSpecial property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNameOrTextOrSpecial().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * </p>
     *
     * @return The value of the nameOrTextOrSpecial property.
     */
    public List<JAXBElement<?>> getNameOrTextOrSpecial() {
        if (nameOrTextOrSpecial == null) {
            nameOrTextOrSpecial = new ArrayList<>();
        }
        return this.nameOrTextOrSpecial;
    }

    /**
     * Gets the value of the optional property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOptional(String value) {
        this.optional = value;
    }

}
