//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for itemType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="itemType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded" minOccurs="0">
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="type" type="{}itemEnum"/>
 *         <element name="magic" type="{}boolean"/>
 *         <element name="detail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="weight" type="{}double"/>
 *         <element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="roll" type="{}roll"/>
 *         <element name="value" type="{}double"/>
 *         <element name="modifier" type="{}modifierType"/>
 *         <element name="ac" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="strength" type="{}integer"/>
 *         <element name="stealth" type="{}boolean"/>
 *         <element name="dmg1" type="{}roll"/>
 *         <element name="dmg2" type="{}roll"/>
 *         <element name="dmgType" type="{}damageEnum"/>
 *         <element name="property" type="{}propertyList"/>
 *         <element name="range" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = {
        "nameOrTypeOrMagic"
})
public class ItemType {

    @XmlElementRefs({
            @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "magic", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "detail", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "weight", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "text", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "roll", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "value", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "modifier", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "ac", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "strength", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "stealth", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dmg1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dmg2", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dmgType", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "property", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "range", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> nameOrTypeOrMagic;

    /**
     * Gets the value of the nameOrTypeOrMagic property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrTypeOrMagic property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNameOrTypeOrMagic().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ItemEnum }{@code >}
     * {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * </p>
     *
     * @return The value of the nameOrTypeOrMagic property.
     */
    public List<JAXBElement<?>> getNameOrTypeOrMagic() {
        if (nameOrTypeOrMagic == null) {
            nameOrTypeOrMagic = new ArrayList<>();
        }
        return this.nameOrTypeOrMagic;
    }

}
