//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for monsterType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="monsterType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded" minOccurs="0">
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="size" type="{}sizeEnum"/>
 *         <element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="alignment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="ac" type="{}acType"/>
 *         <element name="hp" type="{}hpType"/>
 *         <element name="speed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="str" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="dex" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="con" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="int" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="wis" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="cha" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="save" type="{}abilityBonusList"/>
 *         <element name="skill" type="{}skillBonusList"/>
 *         <element name="resist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="vulnerable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="immune" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="conditionImmune" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="senses" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="passive" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="languages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="cr" type="{}crType"/>
 *         <element name="trait" type="{}traitType"/>
 *         <element name="action" type="{}traitType"/>
 *         <element name="legendary" type="{}traitType"/>
 *         <element name="reaction" type="{}traitType"/>
 *         <element name="spells" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="slots" type="{}slotsType"/>
 *         <element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "monsterType", propOrder = {
        "nameOrSizeOrType"
})
public class MonsterType {

    @XmlElementRefs({
            @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "size", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "type", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "alignment", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "ac", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "hp", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "speed", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "str", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dex", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "con", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "int", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "wis", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "cha", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "save", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "skill", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "resist", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "vulnerable", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "immune", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "conditionImmune", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "senses", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "passive", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "languages", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "cr", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "trait", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "action", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "legendary", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "reaction", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "spells", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "slots", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "description", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "environment", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> nameOrSizeOrType;

    /**
     * Gets the value of the nameOrSizeOrType property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrSizeOrType property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNameOrSizeOrType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SizeEnum }{@code >}
     * {@link JAXBElement }{@code <}{@link SlotsType }{@code >}
     * {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     * {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     * {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     * {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * </p>
     *
     * @return The value of the nameOrSizeOrType property.
     */
    public List<JAXBElement<?>> getNameOrSizeOrType() {
        if (nameOrSizeOrType == null) {
            nameOrSizeOrType = new ArrayList<>();
        }
        return this.nameOrSizeOrType;
    }

}
