//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.randomaccessguy.fctofvttconverter.template.fightclub package.
 * <p>An ObjectFactory allows you to programmatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Compendium_QNAME = new QName("", "compendium");
    private static final QName _RaceTypeName_QNAME = new QName("", "name");
    private static final QName _RaceTypeSize_QNAME = new QName("", "size");
    private static final QName _RaceTypeSpeed_QNAME = new QName("", "speed");
    private static final QName _RaceTypeAbility_QNAME = new QName("", "ability");
    private static final QName _RaceTypeSpellAbility_QNAME = new QName("", "spellAbility");
    private static final QName _RaceTypeProficiency_QNAME = new QName("", "proficiency");
    private static final QName _RaceTypeTrait_QNAME = new QName("", "trait");
    private static final QName _RaceTypeModifier_QNAME = new QName("", "modifier");
    private static final QName _ItemTypeType_QNAME = new QName("", "type");
    private static final QName _ItemTypeMagic_QNAME = new QName("", "magic");
    private static final QName _ItemTypeDetail_QNAME = new QName("", "detail");
    private static final QName _ItemTypeWeight_QNAME = new QName("", "weight");
    private static final QName _ItemTypeText_QNAME = new QName("", "text");
    private static final QName _ItemTypeRoll_QNAME = new QName("", "roll");
    private static final QName _ItemTypeValue_QNAME = new QName("", "value");
    private static final QName _ItemTypeAc_QNAME = new QName("", "ac");
    private static final QName _ItemTypeStrength_QNAME = new QName("", "strength");
    private static final QName _ItemTypeStealth_QNAME = new QName("", "stealth");
    private static final QName _ItemTypeDmg1_QNAME = new QName("", "dmg1");
    private static final QName _ItemTypeDmg2_QNAME = new QName("", "dmg2");
    private static final QName _ItemTypeDmgType_QNAME = new QName("", "dmgType");
    private static final QName _ItemTypeProperty_QNAME = new QName("", "property");
    private static final QName _ItemTypeRange_QNAME = new QName("", "range");
    private static final QName _ClassTypeHd_QNAME = new QName("", "hd");
    private static final QName _ClassTypeNumSkills_QNAME = new QName("", "numSkills");
    private static final QName _ClassTypeAutolevel_QNAME = new QName("", "autolevel");
    private static final QName _ClassTypeArmor_QNAME = new QName("", "armor");
    private static final QName _ClassTypeWeapons_QNAME = new QName("", "weapons");
    private static final QName _ClassTypeTools_QNAME = new QName("", "tools");
    private static final QName _ClassTypeSlotsReset_QNAME = new QName("", "slotsReset");
    private static final QName _ClassTypeWealth_QNAME = new QName("", "wealth");
    private static final QName _AutolevelTypeFeature_QNAME = new QName("", "feature");
    private static final QName _AutolevelTypeSlots_QNAME = new QName("", "slots");
    private static final QName _AutolevelTypeCounter_QNAME = new QName("", "counter");
    private static final QName _FeatureTypeSpecial_QNAME = new QName("", "special");
    private static final QName _FeatTypePrerequisite_QNAME = new QName("", "prerequisite");
    private static final QName _SpellTypeLevel_QNAME = new QName("", "level");
    private static final QName _SpellTypeSchool_QNAME = new QName("", "school");
    private static final QName _SpellTypeRitual_QNAME = new QName("", "ritual");
    private static final QName _SpellTypeTime_QNAME = new QName("", "time");
    private static final QName _SpellTypeComponents_QNAME = new QName("", "components");
    private static final QName _SpellTypeDuration_QNAME = new QName("", "duration");
    private static final QName _SpellTypeClasses_QNAME = new QName("", "classes");
    private static final QName _SpellTypeSource_QNAME = new QName("", "source");
    private static final QName _MonsterTypeAlignment_QNAME = new QName("", "alignment");
    private static final QName _MonsterTypeHp_QNAME = new QName("", "hp");
    private static final QName _MonsterTypeStr_QNAME = new QName("", "str");
    private static final QName _MonsterTypeDex_QNAME = new QName("", "dex");
    private static final QName _MonsterTypeCon_QNAME = new QName("", "con");
    private static final QName _MonsterTypeInt_QNAME = new QName("", "int");
    private static final QName _MonsterTypeWis_QNAME = new QName("", "wis");
    private static final QName _MonsterTypeCha_QNAME = new QName("", "cha");
    private static final QName _MonsterTypeSave_QNAME = new QName("", "save");
    private static final QName _MonsterTypeSkill_QNAME = new QName("", "skill");
    private static final QName _MonsterTypeResist_QNAME = new QName("", "resist");
    private static final QName _MonsterTypeVulnerable_QNAME = new QName("", "vulnerable");
    private static final QName _MonsterTypeImmune_QNAME = new QName("", "immune");
    private static final QName _MonsterTypeConditionImmune_QNAME = new QName("", "conditionImmune");
    private static final QName _MonsterTypeSenses_QNAME = new QName("", "senses");
    private static final QName _MonsterTypePassive_QNAME = new QName("", "passive");
    private static final QName _MonsterTypeLanguages_QNAME = new QName("", "languages");
    private static final QName _MonsterTypeCr_QNAME = new QName("", "cr");
    private static final QName _MonsterTypeAction_QNAME = new QName("", "action");
    private static final QName _MonsterTypeLegendary_QNAME = new QName("", "legendary");
    private static final QName _MonsterTypeReaction_QNAME = new QName("", "reaction");
    private static final QName _MonsterTypeSpells_QNAME = new QName("", "spells");
    private static final QName _MonsterTypeDescription_QNAME = new QName("", "description");
    private static final QName _MonsterTypeEnvironment_QNAME = new QName("", "environment");
    private static final QName _TraitTypeAttack_QNAME = new QName("", "attack");
    private static final QName _TraitTypeRecharge_QNAME = new QName("", "recharge");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.randomaccessguy.fctofvttconverter.template.fightclub
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CompendiumType }
     *
     * @return the new instance of {@link CompendiumType }
     */
    public CompendiumType createCompendiumType() {
        return new CompendiumType();
    }

    /**
     * Create an instance of {@link ModifierType }
     *
     * @return the new instance of {@link ModifierType }
     */
    public ModifierType createModifierType() {
        return new ModifierType();
    }

    /**
     * Create an instance of {@link TraitType }
     *
     * @return the new instance of {@link TraitType }
     */
    public TraitType createTraitType() {
        return new TraitType();
    }

    /**
     * Create an instance of {@link SlotsType }
     *
     * @return the new instance of {@link SlotsType }
     */
    public SlotsType createSlotsType() {
        return new SlotsType();
    }

    /**
     * Create an instance of {@link MonsterType }
     *
     * @return the new instance of {@link MonsterType }
     */
    public MonsterType createMonsterType() {
        return new MonsterType();
    }

    /**
     * Create an instance of {@link SpellType }
     *
     * @return the new instance of {@link SpellType }
     */
    public SpellType createSpellType() {
        return new SpellType();
    }

    /**
     * Create an instance of {@link BackgroundType }
     *
     * @return the new instance of {@link BackgroundType }
     */
    public BackgroundType createBackgroundType() {
        return new BackgroundType();
    }

    /**
     * Create an instance of {@link FeatType }
     *
     * @return the new instance of {@link FeatType }
     */
    public FeatType createFeatType() {
        return new FeatType();
    }

    /**
     * Create an instance of {@link FeatureType }
     *
     * @return the new instance of {@link FeatureType }
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link CounterType }
     *
     * @return the new instance of {@link CounterType }
     */
    public CounterType createCounterType() {
        return new CounterType();
    }

    /**
     * Create an instance of {@link AutolevelType }
     *
     * @return the new instance of {@link AutolevelType }
     */
    public AutolevelType createAutolevelType() {
        return new AutolevelType();
    }

    /**
     * Create an instance of {@link ClassType }
     *
     * @return the new instance of {@link ClassType }
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link ItemType }
     *
     * @return the new instance of {@link ItemType }
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link RaceType }
     *
     * @return the new instance of {@link RaceType }
     */
    public RaceType createRaceType() {
        return new RaceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompendiumType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link CompendiumType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "compendium")
    public JAXBElement<CompendiumType> createCompendium(CompendiumType value) {
        return new JAXBElement<>(_Compendium_QNAME, CompendiumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = RaceType.class)
    public JAXBElement<String> createRaceTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SizeEnum }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link SizeEnum }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "size", scope = RaceType.class)
    public JAXBElement<SizeEnum> createRaceTypeSize(SizeEnum value) {
        return new JAXBElement<>(_RaceTypeSize_QNAME, SizeEnum.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "speed", scope = RaceType.class)
    public JAXBElement<BigInteger> createRaceTypeSpeed(BigInteger value) {
        return new JAXBElement<>(_RaceTypeSpeed_QNAME, BigInteger.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ability", scope = RaceType.class)
    public JAXBElement<String> createRaceTypeAbility(String value) {
        return new JAXBElement<>(_RaceTypeAbility_QNAME, String.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "spellAbility", scope = RaceType.class)
    public JAXBElement<String> createRaceTypeSpellAbility(String value) {
        return new JAXBElement<>(_RaceTypeSpellAbility_QNAME, String.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = RaceType.class)
    public JAXBElement<String> createRaceTypeProficiency(String value) {
        return new JAXBElement<>(_RaceTypeProficiency_QNAME, String.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "trait", scope = RaceType.class)
    public JAXBElement<TraitType> createRaceTypeTrait(TraitType value) {
        return new JAXBElement<>(_RaceTypeTrait_QNAME, TraitType.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = RaceType.class)
    public JAXBElement<ModifierType> createRaceTypeModifier(ModifierType value) {
        return new JAXBElement<>(_RaceTypeModifier_QNAME, ModifierType.class, RaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = ItemType.class)
    public JAXBElement<String> createItemTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemEnum }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ItemEnum }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "type", scope = ItemType.class)
    public JAXBElement<ItemEnum> createItemTypeType(ItemEnum value) {
        return new JAXBElement<>(_ItemTypeType_QNAME, ItemEnum.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "magic", scope = ItemType.class)
    public JAXBElement<String> createItemTypeMagic(String value) {
        return new JAXBElement<>(_ItemTypeMagic_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "detail", scope = ItemType.class)
    public JAXBElement<String> createItemTypeDetail(String value) {
        return new JAXBElement<>(_ItemTypeDetail_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "weight", scope = ItemType.class)
    public JAXBElement<String> createItemTypeWeight(String value) {
        return new JAXBElement<>(_ItemTypeWeight_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "text", scope = ItemType.class)
    public JAXBElement<String> createItemTypeText(String value) {
        return new JAXBElement<>(_ItemTypeText_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "roll", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRoll(String value) {
        return new JAXBElement<>(_ItemTypeRoll_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "value", scope = ItemType.class)
    public JAXBElement<String> createItemTypeValue(String value) {
        return new JAXBElement<>(_ItemTypeValue_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = ItemType.class)
    public JAXBElement<ModifierType> createItemTypeModifier(ModifierType value) {
        return new JAXBElement<>(_RaceTypeModifier_QNAME, ModifierType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ac", scope = ItemType.class)
    public JAXBElement<BigInteger> createItemTypeAc(BigInteger value) {
        return new JAXBElement<>(_ItemTypeAc_QNAME, BigInteger.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "strength", scope = ItemType.class)
    public JAXBElement<String> createItemTypeStrength(String value) {
        return new JAXBElement<>(_ItemTypeStrength_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "stealth", scope = ItemType.class)
    public JAXBElement<String> createItemTypeStealth(String value) {
        return new JAXBElement<>(_ItemTypeStealth_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "dmg1", scope = ItemType.class)
    public JAXBElement<String> createItemTypeDmg1(String value) {
        return new JAXBElement<>(_ItemTypeDmg1_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "dmg2", scope = ItemType.class)
    public JAXBElement<String> createItemTypeDmg2(String value) {
        return new JAXBElement<>(_ItemTypeDmg2_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "dmgType", scope = ItemType.class)
    public JAXBElement<String> createItemTypeDmgType(String value) {
        return new JAXBElement<>(_ItemTypeDmgType_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "property", scope = ItemType.class)
    public JAXBElement<String> createItemTypeProperty(String value) {
        return new JAXBElement<>(_ItemTypeProperty_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "range", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRange(String value) {
        return new JAXBElement<>(_ItemTypeRange_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = ClassType.class)
    public JAXBElement<String> createClassTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "hd", scope = ClassType.class)
    public JAXBElement<BigInteger> createClassTypeHd(BigInteger value) {
        return new JAXBElement<>(_ClassTypeHd_QNAME, BigInteger.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = ClassType.class)
    public JAXBElement<String> createClassTypeProficiency(String value) {
        return new JAXBElement<>(_RaceTypeProficiency_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "spellAbility", scope = ClassType.class)
    public JAXBElement<String> createClassTypeSpellAbility(String value) {
        return new JAXBElement<>(_RaceTypeSpellAbility_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "numSkills", scope = ClassType.class)
    public JAXBElement<String> createClassTypeNumSkills(String value) {
        return new JAXBElement<>(_ClassTypeNumSkills_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutolevelType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link AutolevelType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "autolevel", scope = ClassType.class)
    public JAXBElement<AutolevelType> createClassTypeAutolevel(AutolevelType value) {
        return new JAXBElement<>(_ClassTypeAutolevel_QNAME, AutolevelType.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "armor", scope = ClassType.class)
    public JAXBElement<String> createClassTypeArmor(String value) {
        return new JAXBElement<>(_ClassTypeArmor_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "weapons", scope = ClassType.class)
    public JAXBElement<String> createClassTypeWeapons(String value) {
        return new JAXBElement<>(_ClassTypeWeapons_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "tools", scope = ClassType.class)
    public JAXBElement<String> createClassTypeTools(String value) {
        return new JAXBElement<>(_ClassTypeTools_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetEnum }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ResetEnum }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "slotsReset", scope = ClassType.class)
    public JAXBElement<ResetEnum> createClassTypeSlotsReset(ResetEnum value) {
        return new JAXBElement<>(_ClassTypeSlotsReset_QNAME, ResetEnum.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "wealth", scope = ClassType.class)
    public JAXBElement<String> createClassTypeWealth(String value) {
        return new JAXBElement<>(_ClassTypeWealth_QNAME, String.class, ClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeatureType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link FeatureType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "feature", scope = AutolevelType.class)
    public JAXBElement<FeatureType> createAutolevelTypeFeature(FeatureType value) {
        return new JAXBElement<>(_AutolevelTypeFeature_QNAME, FeatureType.class, AutolevelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlotsType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link SlotsType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "slots", scope = AutolevelType.class)
    public JAXBElement<SlotsType> createAutolevelTypeSlots(SlotsType value) {
        return new JAXBElement<>(_AutolevelTypeSlots_QNAME, SlotsType.class, AutolevelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CounterType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link CounterType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "counter", scope = AutolevelType.class)
    public JAXBElement<CounterType> createAutolevelTypeCounter(CounterType value) {
        return new JAXBElement<>(_AutolevelTypeCounter_QNAME, CounterType.class, AutolevelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = FeatureType.class)
    public JAXBElement<String> createFeatureTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, FeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "text", scope = FeatureType.class)
    public JAXBElement<String> createFeatureTypeText(String value) {
        return new JAXBElement<>(_ItemTypeText_QNAME, String.class, FeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "special", scope = FeatureType.class)
    public JAXBElement<String> createFeatureTypeSpecial(String value) {
        return new JAXBElement<>(_FeatureTypeSpecial_QNAME, String.class, FeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = FeatureType.class)
    public JAXBElement<ModifierType> createFeatureTypeModifier(ModifierType value) {
        return new JAXBElement<>(_RaceTypeModifier_QNAME, ModifierType.class, FeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = FeatureType.class)
    public JAXBElement<String> createFeatureTypeProficiency(String value) {
        return new JAXBElement<>(_RaceTypeProficiency_QNAME, String.class, FeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = FeatType.class)
    public JAXBElement<String> createFeatTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, FeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "prerequisite", scope = FeatType.class)
    public JAXBElement<String> createFeatTypePrerequisite(String value) {
        return new JAXBElement<>(_FeatTypePrerequisite_QNAME, String.class, FeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "special", scope = FeatType.class)
    public JAXBElement<String> createFeatTypeSpecial(String value) {
        return new JAXBElement<>(_FeatureTypeSpecial_QNAME, String.class, FeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "text", scope = FeatType.class)
    public JAXBElement<String> createFeatTypeText(String value) {
        return new JAXBElement<>(_ItemTypeText_QNAME, String.class, FeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = FeatType.class)
    public JAXBElement<String> createFeatTypeProficiency(String value) {
        return new JAXBElement<>(_RaceTypeProficiency_QNAME, String.class, FeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ModifierType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = FeatType.class)
    public JAXBElement<ModifierType> createFeatTypeModifier(ModifierType value) {
        return new JAXBElement<>(_RaceTypeModifier_QNAME, ModifierType.class, FeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = BackgroundType.class)
    public JAXBElement<String> createBackgroundTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, BackgroundType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = BackgroundType.class)
    public JAXBElement<String> createBackgroundTypeProficiency(String value) {
        return new JAXBElement<>(_RaceTypeProficiency_QNAME, String.class, BackgroundType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "trait", scope = BackgroundType.class)
    public JAXBElement<TraitType> createBackgroundTypeTrait(TraitType value) {
        return new JAXBElement<>(_RaceTypeTrait_QNAME, TraitType.class, BackgroundType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "level", scope = SpellType.class)
    public JAXBElement<BigInteger> createSpellTypeLevel(BigInteger value) {
        return new JAXBElement<>(_SpellTypeLevel_QNAME, BigInteger.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchoolEnum }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link SchoolEnum }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "school", scope = SpellType.class)
    public JAXBElement<SchoolEnum> createSpellTypeSchool(SchoolEnum value) {
        return new JAXBElement<>(_SpellTypeSchool_QNAME, SchoolEnum.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ritual", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeRitual(String value) {
        return new JAXBElement<>(_SpellTypeRitual_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "time", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeTime(String value) {
        return new JAXBElement<>(_SpellTypeTime_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "range", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeRange(String value) {
        return new JAXBElement<>(_ItemTypeRange_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "components", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeComponents(String value) {
        return new JAXBElement<>(_SpellTypeComponents_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "duration", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeDuration(String value) {
        return new JAXBElement<>(_SpellTypeDuration_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "classes", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeClasses(String value) {
        return new JAXBElement<>(_SpellTypeClasses_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "source", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeSource(String value) {
        return new JAXBElement<>(_SpellTypeSource_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "text", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeText(String value) {
        return new JAXBElement<>(_ItemTypeText_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "roll", scope = SpellType.class)
    public JAXBElement<String> createSpellTypeRoll(String value) {
        return new JAXBElement<>(_ItemTypeRoll_QNAME, String.class, SpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SizeEnum }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link SizeEnum }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "size", scope = MonsterType.class)
    public JAXBElement<SizeEnum> createMonsterTypeSize(SizeEnum value) {
        return new JAXBElement<>(_RaceTypeSize_QNAME, SizeEnum.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "type", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeType(String value) {
        return new JAXBElement<>(_ItemTypeType_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "alignment", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeAlignment(String value) {
        return new JAXBElement<>(_MonsterTypeAlignment_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ac", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeAc(String value) {
        return new JAXBElement<>(_ItemTypeAc_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "hp", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeHp(String value) {
        return new JAXBElement<>(_MonsterTypeHp_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "speed", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeSpeed(String value) {
        return new JAXBElement<>(_RaceTypeSpeed_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "str", scope = MonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeStr(BigInteger value) {
        return new JAXBElement<>(_MonsterTypeStr_QNAME, BigInteger.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "dex", scope = MonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeDex(BigInteger value) {
        return new JAXBElement<>(_MonsterTypeDex_QNAME, BigInteger.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "con", scope = MonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeCon(BigInteger value) {
        return new JAXBElement<>(_MonsterTypeCon_QNAME, BigInteger.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "int", scope = MonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeInt(BigInteger value) {
        return new JAXBElement<>(_MonsterTypeInt_QNAME, BigInteger.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "wis", scope = MonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeWis(BigInteger value) {
        return new JAXBElement<>(_MonsterTypeWis_QNAME, BigInteger.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "cha", scope = MonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeCha(BigInteger value) {
        return new JAXBElement<>(_MonsterTypeCha_QNAME, BigInteger.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "save", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeSave(String value) {
        return new JAXBElement<>(_MonsterTypeSave_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "skill", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeSkill(String value) {
        return new JAXBElement<>(_MonsterTypeSkill_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "resist", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeResist(String value) {
        return new JAXBElement<>(_MonsterTypeResist_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "vulnerable", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeVulnerable(String value) {
        return new JAXBElement<>(_MonsterTypeVulnerable_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "immune", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeImmune(String value) {
        return new JAXBElement<>(_MonsterTypeImmune_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "conditionImmune", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeConditionImmune(String value) {
        return new JAXBElement<>(_MonsterTypeConditionImmune_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "senses", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeSenses(String value) {
        return new JAXBElement<>(_MonsterTypeSenses_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "passive", scope = MonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypePassive(BigInteger value) {
        return new JAXBElement<>(_MonsterTypePassive_QNAME, BigInteger.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "languages", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeLanguages(String value) {
        return new JAXBElement<>(_MonsterTypeLanguages_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "cr", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeCr(String value) {
        return new JAXBElement<>(_MonsterTypeCr_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "trait", scope = MonsterType.class)
    public JAXBElement<TraitType> createMonsterTypeTrait(TraitType value) {
        return new JAXBElement<>(_RaceTypeTrait_QNAME, TraitType.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "action", scope = MonsterType.class)
    public JAXBElement<TraitType> createMonsterTypeAction(TraitType value) {
        return new JAXBElement<>(_MonsterTypeAction_QNAME, TraitType.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "legendary", scope = MonsterType.class)
    public JAXBElement<TraitType> createMonsterTypeLegendary(TraitType value) {
        return new JAXBElement<>(_MonsterTypeLegendary_QNAME, TraitType.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link TraitType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "reaction", scope = MonsterType.class)
    public JAXBElement<TraitType> createMonsterTypeReaction(TraitType value) {
        return new JAXBElement<>(_MonsterTypeReaction_QNAME, TraitType.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "spells", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeSpells(String value) {
        return new JAXBElement<>(_MonsterTypeSpells_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlotsType }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link SlotsType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "slots", scope = MonsterType.class)
    public JAXBElement<SlotsType> createMonsterTypeSlots(SlotsType value) {
        return new JAXBElement<>(_AutolevelTypeSlots_QNAME, SlotsType.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "description", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeDescription(String value) {
        return new JAXBElement<>(_MonsterTypeDescription_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "environment", scope = MonsterType.class)
    public JAXBElement<String> createMonsterTypeEnvironment(String value) {
        return new JAXBElement<>(_MonsterTypeEnvironment_QNAME, String.class, MonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = TraitType.class)
    public JAXBElement<String> createTraitTypeName(String value) {
        return new JAXBElement<>(_RaceTypeName_QNAME, String.class, TraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "text", scope = TraitType.class)
    public JAXBElement<String> createTraitTypeText(String value) {
        return new JAXBElement<>(_ItemTypeText_QNAME, String.class, TraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "attack", scope = TraitType.class)
    public JAXBElement<String> createTraitTypeAttack(String value) {
        return new JAXBElement<>(_TraitTypeAttack_QNAME, String.class, TraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = TraitType.class)
    public JAXBElement<String> createTraitTypeProficiency(String value) {
        return new JAXBElement<>(_RaceTypeProficiency_QNAME, String.class, TraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "special", scope = TraitType.class)
    public JAXBElement<String> createTraitTypeSpecial(String value) {
        return new JAXBElement<>(_FeatureTypeSpecial_QNAME, String.class, TraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "recharge", scope = TraitType.class)
    public JAXBElement<String> createTraitTypeRecharge(String value) {
        return new JAXBElement<>(_TraitTypeRecharge_QNAME, String.class, TraitType.class, value);
    }

}
