//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for schoolEnum</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="schoolEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="A"/>
 *     <enumeration value="C"/>
 *     <enumeration value="D"/>
 *     <enumeration value="EN"/>
 *     <enumeration value="EV"/>
 *     <enumeration value="I"/>
 *     <enumeration value="N"/>
 *     <enumeration value="T"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "schoolEnum")
@XmlEnum
public enum SchoolEnum {

    A,
    C,
    D,
    EN,
    EV,
    I,
    N,
    T;

    public String value() {
        return name();
    }

    public static SchoolEnum fromValue(String v) {
        return valueOf(v);
    }

}
