//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.randomaccessguy.fightclubtofoundryconverter.template.fightclub;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for spellType complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType name="spellType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice maxOccurs="unbounded">
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="level" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="school" type="{}schoolEnum" minOccurs="0"/>
 *         <element name="ritual" type="{}boolean"/>
 *         <element name="time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="range" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="components" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="duration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="classes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="text" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="roll" type="{}roll" maxOccurs="unbounded" minOccurs="0"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spellType", propOrder = {
        "nameOrLevelOrSchool"
})
public class SpellType {

    @XmlElementRefs({
            @XmlElementRef(name = "name", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "level", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "school", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "ritual", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "time", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "range", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "components", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "duration", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "classes", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "source", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "text", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "roll", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> nameOrLevelOrSchool;

    /**
     * Gets the value of the nameOrLevelOrSchool property.
     *
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrLevelOrSchool property.</p>
     *
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNameOrLevelOrSchool().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SchoolEnum }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * </p>
     *
     * @return The value of the nameOrLevelOrSchool property.
     */
    public List<JAXBElement<?>> getNameOrLevelOrSchool() {
        if (nameOrLevelOrSchool == null) {
            nameOrLevelOrSchool = new ArrayList<>();
        }
        return this.nameOrLevelOrSchool;
    }

}
